var nodesdata = [
    { "id": "0",  "label": "理科",  "customProperty": ""}, 
    { "id": "1000",  "label": "生命",  "customProperty": ""}, 
    { "id": "1100",  "label": "生物の構造と機能",  "customProperty": ""}, 
    { "id": "1101",  "label": "しぜんのかんさつ",  "customProperty": "いきもののすがた"}, 
    { "id": "1102",  "label": "植物の育ち方（１）",  "customProperty": "たねまき"}, 
    { "id": "1103",  "label": "植物の育ち方（２）",  "customProperty": "葉・くき・根"}, 
    { "id": "1104",  "label": "植物の育ち方（３）",  "customProperty": "花"}, 
    { "id": "1105",  "label": "植物の育ち方（４）",  "customProperty": "花がさいた後"}, 
    { "id": "1106",  "label": "こん虫の育ち方",  "customProperty": "チョウの育ち方・こん虫の体のつくり・こん虫の育ち方"}, 
    { "id": "1107",  "label": "動物のすみか",  "customProperty": "動物のすみか"}, 
    { "id": "1108",  "label": "わたしたちの体と運動",  "customProperty": "うでのほねのつくり・うでが動くしくみ・体全体のほねと筋肉"}, 
    { "id": "1109",  "label": "体のつくりとはたらき",  "customProperty": "吸った空気のゆくえ・血液に取り入れられた酸素のゆくえ・食べたもののゆくえ"}, 
    { "id": "1110",  "label": "植物の成長と日光の関わり",  "customProperty": "成長と日光の関わり"}, 
    { "id": "1111",  "label": "植物の成長と水の関わり",  "customProperty": "成長と水の関わり"}, 
    { "id": "1112",  "label": "生物の観察と分類の仕方",  "customProperty": "生物の観察・生物の特徴と分類の仕方"}, 
    { "id": "1113",  "label": "生物の体の共通点と相違点",  "customProperty": "植物の体の共通点と相違点・動物の体の共通点と相違点"}, 
    { "id": "1114",  "label": "生物と細胞",  "customProperty": "生物と細胞"}, 
    { "id": "1115",  "label": "植物の体のつくりと働き",  "customProperty": "葉・茎・根のつくりと働き"}, 
    { "id": "1116",  "label": "動物の体のつくりと働き",  "customProperty": "生命を維持する働き・刺激と反応"}, 
    { "id": "1200",  "label": "生命の連続性",  "customProperty": ""}, 
    { "id": "1201",  "label": "季節と生物（１）",  "customProperty": "春の始まり"}, 
    { "id": "1202",  "label": "季節と生物（２）",  "customProperty": "春　1年間の観察・生物の春のようす"}, 
    { "id": "1203",  "label": "季節と生物（３）",  "customProperty": "夏"}, 
    { "id": "1204",  "label": "季節と生物（４）",  "customProperty": "夏の終わり"}, 
    { "id": "1205",  "label": "季節と生物（５）",  "customProperty": "秋"}, 
    { "id": "1206",  "label": "季節と生物（６）",  "customProperty": "冬　冬の生物のようす・1年間を振り返って"}, 
    { "id": "1207",  "label": "季節と生物（７）",  "customProperty": "春のおとずれ"}, 
    { "id": "1208",  "label": "生命のつながり　植物の発芽と成長",  "customProperty": "・発芽の条件・発芽と養分・植物の成長の条件"}, 
    { "id": "1209",  "label": "生命のつながり　植物の実や種子のでき方",  "customProperty": "・花のつくり・受粉の役わり"}, 
    { "id": "1210",  "label": "生命のつながり　メダカのたんじょう",  "customProperty": "・メダカのたまごの変化"}, 
    { "id": "1211",  "label": "生命のつながり　人のたんじょう",  "customProperty": "・母親のおなかの中での子どもの成長"}, 
    { "id": "1212",  "label": "生物の成長と殖え方",  "customProperty": "・細胞分裂と生物の成長・生物の殖え方"}, 
    { "id": "1213",  "label": "遺伝の規則性と遺伝子",  "customProperty": "・遺伝の規則性と遺伝子"}, 
    { "id": "1214",  "label": "生物の種類の多様性と進化",  "customProperty": "・生物の種類の多様性と進化"}, 
    { "id": "1300",  "label": "生物と環境の関わり",  "customProperty": ""}, 
    { "id": "1301",  "label": "私たちの生活と環境",  "customProperty": ""}, 
    { "id": "1302",  "label": "生物どうしの関わり",  "customProperty": "食べ物を通した生物どうしの関わり・空気を通した生物どうしの関わり・水と生物との関わり"}, 
    { "id": "1303",  "label": "生物と地球環境",  "customProperty": "生物と環境（水・空気・ほかの生物）との関わり・地球を守る"}, 
    { "id": "1304",  "label": "生物と環境",  "customProperty": "自然界の釣り合い・自然環境の調査と環境保全・地域の自然災害"}, 
    { "id": "1305",  "label": "自然環境の保全と科学技術の利用",  "customProperty": "自然環境の保全と科学技術の利用"}, 
    { "id": "2000",  "label": "地球",  "customProperty": ""}, 
    { "id": "2100",  "label": "地球内部と地表面の変動",  "customProperty": ""}, 
    { "id": "2101",  "label": "雨水のゆくえ",  "customProperty": "流れる水のゆくえ・土のつぶの大きさと水のしみこみ・空気中に出ていく水"}, 
    { "id": "2102",  "label": "流れる水のはたらきと土地の変化",  "customProperty": "流れる水のはたらき・川と川原の石のようす・流れる水と変化する土地"}, 
    { "id": "2103",  "label": "土地のつくりと変化",  "customProperty": "土地をつくっているもの・地層のでき方・火山活動や地震による土地の変化"}, 
    { "id": "2104",  "label": "身近な地形や地層、岩石の観察",  "customProperty": "身近な地形や地層、岩石の観察"}, 
    { "id": "2105",  "label": "地層の重なりと過去の様子",  "customProperty": "地層の重なりと過去の様子"}, 
    { "id": "2106",  "label": "火山と地震",  "customProperty": "火山活動と火成岩・地震の伝わり方と地球内部の働き"}, 
    { "id": "2107",  "label": "自然の恵みと火山災害・地震災害",  "customProperty": "自然の恵みと火山災害・地震災害"}, 
    { "id": "2200",  "label": "地球の大気と水の循環",  "customProperty": ""}, 
    { "id": "2201",  "label": "天気と気温",  "customProperty": "天気と気温"}, 
    { "id": "2202",  "label": "天気と情報（１）天気の変化",  "customProperty": "天気と雲・天気の変化"}, 
    { "id": "2203",  "label": "天気と情報（２）台風と防災",  "customProperty": "台風の接近と天気"}, 
    { "id": "2204",  "label": "気象観測",  "customProperty": "気象要素・気象観測"}, 
    { "id": "2205",  "label": "天気の変化",  "customProperty": "霧や雲の発生・前線の通過と天気の変化"}, 
    { "id": "2206",  "label": "日本の気象",  "customProperty": "日本の天気の特徴・大気の動きと海洋の影響"}, 
    { "id": "2207",  "label": "自然の恵みと気象災害",  "customProperty": "自然の恵みと気象災害"}, 
    { "id": "2300",  "label": "地球と天体の運動",  "customProperty": ""}, 
    { "id": "2301",  "label": "地面のようすと太陽",  "customProperty": "かげのでき方と太陽のいち・日なたと日かげの地面の様子"}, 
    { "id": "2302",  "label": "星や月（１）星の明るさや色",  "customProperty": ""}, 
    { "id": "2303",  "label": "星や月（２）月と星の位置の変化",  "customProperty": "月の位置の変化・星の位置の変化"}, 
    { "id": "2304",  "label": "星や月（３）",  "customProperty": "冬の星"}, 
    { "id": "2305",  "label": "月と太陽",  "customProperty": "月の形とその変化"}, 
    { "id": "2306",  "label": "天体の動きと地球の自転・公転",  "customProperty": "日周運動と自転・年周運動と恒星・月や金星の運動と見え方"}, 
    { "id": "3000",  "label": "エネルギー",  "customProperty": ""}, 
    { "id": "3100",  "label": "エネルギーの捉え方",  "customProperty": ""}, 
    { "id": "3101",  "label": "ゴムや風の力",  "customProperty": "ものを動かすゴム・ものを動かす風"}, 
    { "id": "3102",  "label": "音のふしぎ",  "customProperty": "音の出方・つたわり方"}, 
    { "id": "3103",  "label": "太陽の光",  "customProperty": "日光の進み方・日光をあてたところの明るさとあたたかさ"}, 
    { "id": "3104",  "label": "ふりこの動き",  "customProperty": "ふりこの１往復する時間"}, 
    { "id": "3105",  "label": "てこのはたらき",  "customProperty": "てこのはたらき・てこのはたらきを利用した道具"}, 
    { "id": "3106",  "label": "力の働き",  "customProperty": "力の働き"}, 
    { "id": "3107",  "label": "光と音",  "customProperty": "光の反射・屈折・凸レンズの働き・音の性質"}, 
    { "id": "3108",  "label": "電流",  "customProperty": "回路と電流、電圧・電流・電圧と抵抗・電気とそのエネルギー・静電気と電流"}, 
    { "id": "3109",  "label": "電流と磁界",  "customProperty": "電流がつくる磁界・磁界中の電流が受ける力・電磁誘導と発電"}, 
    { "id": "3110",  "label": "力の釣り合いと合成・分解",  "customProperty": "水中の物体に働く力・力の合成、分解"}, 
    { "id": "3111",  "label": "運動の規則性",  "customProperty": "運動の速さと向き・力の運動"}, 
    { "id": "3112",  "label": "力学的エネルギー",  "customProperty": "仕事とエネルギー・力学的エネルギー保存"}, 
    { "id": "3200",  "label": "エネルギーの変換と保存",  "customProperty": ""}, 
    { "id": "3201",  "label": "じしゃくのふじぎ",  "customProperty": "じしゃくに引きつけられるもの・じしゃくと鉄"}, 
    { "id": "3202",  "label": "電気の通り道",  "customProperty": "電気の通り道・電気を通すもの・通さないもの"}, 
    { "id": "3203",  "label": "電流のはたらき",  "customProperty": "かん電池のはたらき・かん電池のつなげ方"}, 
    { "id": "3204",  "label": "電磁石の性質",  "customProperty": "電磁石の極・電磁石の強さ"}, 
    { "id": "3205",  "label": "私たちの生活と電気",  "customProperty": "つくる電気、ためる電気・身の回りの電気の利用・使う電気の量とはたらき"}, 
    { "id": "3206",  "label": "エネルギーと物質",  "customProperty": "エネルギーとエネルギー資源・様々な物質とその利用・科学技術の発展"}, 
    { "id": "3300",  "label": "エネルギー資源の有効活用",  "customProperty": ""}, 
    { "id": "3301",  "label": "自然環境の保全と科学技術の利用",  "customProperty": "自然環境の保全と科学技術の利用"}, 
    { "id": "4000",  "label": "粒子",  "customProperty": ""}, 
    { "id": "4100",  "label": "粒子の存在",  "customProperty": ""}, 
    { "id": "4101",  "label": "とじこめた空気や水",  "customProperty": "とじこめた空気・とじこめた水"}, 
    { "id": "4102",  "label": "ものの燃え方",  "customProperty": "ものの燃え方と空気・ものが燃えるときの空気の変化"}, 
    { "id": "4103",  "label": "物質のすがた",  "customProperty": "身の回りの物質とその性質・気体の発生と性質"}, 
    { "id": "4104",  "label": "物質の成り立ち",  "customProperty": "物質の分解・原子、分子"}, 
    { "id": "4105",  "label": "水溶液とイオン",  "customProperty": "原子の成り立ちとイオン・酸、アルカリ・中和と塩"}, 
    { "id": "4106",  "label": "化学変化と電池",  "customProperty": "金属イオン・化学変化と電池"}, 
    { "id": "4200",  "label": "粒子の結合",  "customProperty": ""}, 
    { "id": "4201",  "label": "水よう液の性質",  "customProperty": "水よう液にとけているもの・酸性、中性、アルカリ性の水よう液・金属をとかす水よう液"}, 
    { "id": "4202",  "label": "化学変化",  "customProperty": "化学変化・化学変化における酸化と還元・化学変化と熱"}, 
    { "id": "4203",  "label": "化学変化と物質の質量",  "customProperty": "化学変化と質量の保存・質量変化の規則性"}, 
    { "id": "4300",  "label": "粒子の保存性",  "customProperty": ""}, 
    { "id": "4301",  "label": "ものの重さ",  "customProperty": "もののしゅるいと重さ・ものの形と重さ"}, 
    { "id": "4302",  "label": "もののとけ方",  "customProperty": "とけたもののゆくえ・水にとけるものの量・とかしたもののとり出し方"}, 
    { "id": "4303",  "label": "水溶液",  "customProperty": "水溶液"}, 
    { "id": "4304",  "label": "状態変化",  "customProperty": "状態変化と熱・物質の融点と沸点"}, 
    { "id": "4400",  "label": "粒子のもつエネルギー",  "customProperty": ""}, 
    { "id": "4401",  "label": "ものの温度と体積",  "customProperty": "空気の温度と体積・水の温度と体積・金ぞくの温度と体積"}, 
    { "id": "4402",  "label": "もののあたたまり方",  "customProperty": "金属のあたたまり方・水と空気のあたたまり方"}, 
    { "id": "4403",  "label": "すがたを変える水",  "customProperty": "熱したときの水のようす・冷やしたときの水のようす・温度と水のすがた"}
];

var edgesdata = [
    { "id": "1",  "from": "1000",  "to": "0",  "customProperty": ""}, 
    { "id": "2",  "from": "1100",  "to": "1000",  "customProperty": ""}, 
    { "id": "3",  "from": "1101",  "to": "1100",  "customProperty": ""}, 
    { "id": "4",  "from": "1102",  "to": "1100",  "customProperty": ""}, 
    { "id": "5",  "from": "1103",  "to": "1100",  "customProperty": ""}, 
    { "id": "6",  "from": "1104",  "to": "1100",  "customProperty": ""}, 
    { "id": "7",  "from": "1105",  "to": "1100",  "customProperty": ""}, 
    { "id": "8",  "from": "1106",  "to": "1100",  "customProperty": ""}, 
    { "id": "9",  "from": "1107",  "to": "1100",  "customProperty": ""}, 
    { "id": "10",  "from": "1108",  "to": "1100",  "customProperty": ""}, 
    { "id": "11",  "from": "1109",  "to": "1100",  "customProperty": ""}, 
    { "id": "12",  "from": "1110",  "to": "1100",  "customProperty": ""}, 
    { "id": "13",  "from": "1111",  "to": "1100",  "customProperty": ""}, 
    { "id": "14",  "from": "1112",  "to": "1100",  "customProperty": ""}, 
    { "id": "15",  "from": "1113",  "to": "1100",  "customProperty": ""}, 
    { "id": "16",  "from": "1114",  "to": "1100",  "customProperty": ""}, 
    { "id": "17",  "from": "1115",  "to": "1100",  "customProperty": ""}, 
    { "id": "18",  "from": "1116",  "to": "1100",  "customProperty": ""}, 
    { "id": "19",  "from": "1200",  "to": "1000",  "customProperty": ""}, 
    { "id": "20",  "from": "1201",  "to": "1200",  "customProperty": ""}, 
    { "id": "21",  "from": "1202",  "to": "1200",  "customProperty": ""}, 
    { "id": "22",  "from": "1203",  "to": "1200",  "customProperty": ""}, 
    { "id": "23",  "from": "1204",  "to": "1200",  "customProperty": ""}, 
    { "id": "24",  "from": "1205",  "to": "1200",  "customProperty": ""}, 
    { "id": "25",  "from": "1206",  "to": "1200",  "customProperty": ""}, 
    { "id": "26",  "from": "1207",  "to": "1200",  "customProperty": ""}, 
    { "id": "27",  "from": "1208",  "to": "1200",  "customProperty": ""}, 
    { "id": "28",  "from": "1209",  "to": "1200",  "customProperty": ""}, 
    { "id": "29",  "from": "1210",  "to": "1200",  "customProperty": ""}, 
    { "id": "30",  "from": "1211",  "to": "1200",  "customProperty": ""}, 
    { "id": "31",  "from": "1212",  "to": "1200",  "customProperty": ""}, 
    { "id": "32",  "from": "1213",  "to": "1200",  "customProperty": ""}, 
    { "id": "33",  "from": "1214",  "to": "1200",  "customProperty": ""}, 
    { "id": "34",  "from": "1300",  "to": "1000",  "customProperty": ""}, 
    { "id": "35",  "from": "1301",  "to": "1300",  "customProperty": ""}, 
    { "id": "36",  "from": "1302",  "to": "1300",  "customProperty": ""}, 
    { "id": "37",  "from": "1303",  "to": "1300",  "customProperty": ""}, 
    { "id": "38",  "from": "1304",  "to": "1300",  "customProperty": ""}, 
    { "id": "39",  "from": "1305",  "to": "1300",  "customProperty": ""}, 
    { "id": "40",  "from": "2000",  "to": "0",  "customProperty": ""}, 
    { "id": "41",  "from": "2100",  "to": "2000",  "customProperty": ""}, 
    { "id": "42",  "from": "2101",  "to": "2100",  "customProperty": ""}, 
    { "id": "43",  "from": "2102",  "to": "2100",  "customProperty": ""}, 
    { "id": "44",  "from": "2103",  "to": "2100",  "customProperty": ""}, 
    { "id": "45",  "from": "2104",  "to": "2100",  "customProperty": ""}, 
    { "id": "46",  "from": "2105",  "to": "2100",  "customProperty": ""}, 
    { "id": "47",  "from": "2106",  "to": "2100",  "customProperty": ""}, 
    { "id": "48",  "from": "2107",  "to": "2100",  "customProperty": ""}, 
    { "id": "49",  "from": "2200",  "to": "2000",  "customProperty": ""}, 
    { "id": "50",  "from": "2201",  "to": "2200",  "customProperty": ""}, 
    { "id": "51",  "from": "2202",  "to": "2200",  "customProperty": ""}, 
    { "id": "52",  "from": "2203",  "to": "2200",  "customProperty": ""}, 
    { "id": "53",  "from": "2204",  "to": "2200",  "customProperty": ""}, 
    { "id": "54",  "from": "2205",  "to": "2200",  "customProperty": ""}, 
    { "id": "55",  "from": "2206",  "to": "2200",  "customProperty": ""}, 
    { "id": "56",  "from": "2207",  "to": "2200",  "customProperty": ""}, 
    { "id": "57",  "from": "2300",  "to": "2000",  "customProperty": ""}, 
    { "id": "58",  "from": "2301",  "to": "2300",  "customProperty": ""}, 
    { "id": "59",  "from": "2302",  "to": "2300",  "customProperty": ""}, 
    { "id": "60",  "from": "2303",  "to": "2300",  "customProperty": ""}, 
    { "id": "61",  "from": "2304",  "to": "2300",  "customProperty": ""}, 
    { "id": "62",  "from": "2305",  "to": "2300",  "customProperty": ""}, 
    { "id": "63",  "from": "2306",  "to": "2300",  "customProperty": ""}, 
    { "id": "64",  "from": "3000",  "to": "0",  "customProperty": ""}, 
    { "id": "65",  "from": "3100",  "to": "3000",  "customProperty": ""}, 
    { "id": "66",  "from": "3101",  "to": "3100",  "customProperty": ""}, 
    { "id": "67",  "from": "3102",  "to": "3100",  "customProperty": ""}, 
    { "id": "68",  "from": "3103",  "to": "3100",  "customProperty": ""}, 
    { "id": "69",  "from": "3104",  "to": "3100",  "customProperty": ""}, 
    { "id": "70",  "from": "3105",  "to": "3100",  "customProperty": ""}, 
    { "id": "71",  "from": "3106",  "to": "3100",  "customProperty": ""}, 
    { "id": "72",  "from": "3107",  "to": "3100",  "customProperty": ""}, 
    { "id": "73",  "from": "3108",  "to": "3100",  "customProperty": ""}, 
    { "id": "74",  "from": "3109",  "to": "3100",  "customProperty": ""}, 
    { "id": "75",  "from": "3110",  "to": "3100",  "customProperty": ""}, 
    { "id": "76",  "from": "3111",  "to": "3100",  "customProperty": ""}, 
    { "id": "77",  "from": "3112",  "to": "3100",  "customProperty": ""}, 
    { "id": "78",  "from": "3200",  "to": "3000",  "customProperty": ""}, 
    { "id": "79",  "from": "3201",  "to": "3200",  "customProperty": ""}, 
    { "id": "80",  "from": "3202",  "to": "3200",  "customProperty": ""}, 
    { "id": "81",  "from": "3203",  "to": "3200",  "customProperty": ""}, 
    { "id": "82",  "from": "3204",  "to": "3200",  "customProperty": ""}, 
    { "id": "83",  "from": "3205",  "to": "3200",  "customProperty": ""}, 
    { "id": "84",  "from": "3206",  "to": "3200",  "customProperty": ""}, 
    { "id": "85",  "from": "3300",  "to": "3000",  "customProperty": ""}, 
    { "id": "86",  "from": "3301",  "to": "3300",  "customProperty": ""}, 
    { "id": "87",  "from": "4000",  "to": "0",  "customProperty": ""}, 
    { "id": "88",  "from": "4100",  "to": "4000",  "customProperty": ""}, 
    { "id": "89",  "from": "4101",  "to": "4100",  "customProperty": ""}, 
    { "id": "90",  "from": "4102",  "to": "4100",  "customProperty": ""}, 
    { "id": "91",  "from": "4103",  "to": "4100",  "customProperty": ""}, 
    { "id": "92",  "from": "4104",  "to": "4100",  "customProperty": ""}, 
    { "id": "93",  "from": "4105",  "to": "4100",  "customProperty": ""}, 
    { "id": "94",  "from": "4106",  "to": "4100",  "customProperty": ""}, 
    { "id": "95",  "from": "4200",  "to": "4000",  "customProperty": ""}, 
    { "id": "96",  "from": "4201",  "to": "4200",  "customProperty": ""}, 
    { "id": "97",  "from": "4202",  "to": "4200",  "customProperty": ""}, 
    { "id": "98",  "from": "4203",  "to": "4200",  "customProperty": ""}, 
    { "id": "99",  "from": "4300",  "to": "4000",  "customProperty": ""}, 
    { "id": "100",  "from": "4301",  "to": "4300",  "customProperty": ""}, 
    { "id": "101",  "from": "4302",  "to": "4300",  "customProperty": ""}, 
    { "id": "102",  "from": "4303",  "to": "4300",  "customProperty": ""}, 
    { "id": "103",  "from": "4304",  "to": "4300",  "customProperty": ""}, 
    { "id": "104",  "from": "4400",  "to": "4000",  "customProperty": ""}, 
    { "id": "105",  "from": "4401",  "to": "4400",  "customProperty": ""}, 
    { "id": "106",  "from": "4402",  "to": "4400",  "customProperty": ""}, 
    { "id": "107",  "from": "4403",  "to": "4400",  "customProperty": ""}
];
